version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "detectordag"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-174y4s2qwls0w"
s3_prefix = "detectordag"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
